apiVersion: apps/v1

kind: Deployment

metadata:
  name: board-api
  labels:
    env: dev

spec:
  #replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev

    spec:
      containers:
        - name: board-api
          image: board-api
          ports:
            - name: http
              containerPort: 8080
